version: "3.9"
services:
  kcacldb:
    container_name: kcaclpgdb
    # for production, recommend postgres v15+
    image: "postgres:latest"
    healthcheck:
      test: [ "CMD", "pg_isready", "-q", "-d", "postgres", "-U", "root" ]
      timeout: 45s
      interval: 10s
      retries: 10
    volumes:
      - postgres_data:/var/lib/postgresql/kcacldata
      #- ./sql:/docker-entrypoint-initdb.d/:ro # turn it on, if you need run init DB
    environment:
      TZ: ${TZ}
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
      POSTGRES_DB: ${POSTGRES_DB}
      POSTGRES_HOST: ${DB_HOST}
    networks:
      - kcaclnet
    ports:
      - "${DB_PORT}:5432"

  kc:    
    image: quay.io/keycloak/keycloak:26.0.0    
    command:
      - start
    depends_on:
      - "kcacldb"
    environment:
      JAVA_OPTS_APPEND: >-
        -Dkeycloak.profile.feature.upload_scripts=enabled
        -Xms512m
        -Xmx2048m
        -XX:MetaspaceSize=96M
        -XX:MaxMetaspaceSize=256m
        -Djava.net.preferIPv4Stack=true
        -Djboss.modules.system.pkgs=org.jboss.byteman
      KC_DB: postgres
      KC_DB_PASSWORD: ${POSTGRES_PASSWORD}
      KC_DB_SCHEMA: public
      KC_DB_USERNAME: ${POSTGRES_USER}
      KC_DB_URL_HOST: kcacldb       
      KC_DB_URL_DATABASE: ${POSTGRES_DB}
      KC_HEALTH_ENABLED: 'true'
      KC_HTTP_ENABLED: 'true'
      KC_METRICS_ENABLED: 'true'
      # KC_HOSTNAME: keycloak.com.au
      # KC_HOSTNAME_PORT: 8180      
      KC_PROXY: edge
      KC_BOOTSTRAP_ADMIN_USERNAME: ${KC_ADMIN}
      KC_BOOTSTRAP_ADMIN_PASSWORD: ${KC_ADMIN_PASSWORD}
      PROXY_ADDRESS_FORWARDING: "true"
      CACHE_OWNERS_COUNT: 2
      KC_HOSTNAME_ADMIN: http://localhost:9180
      KC_HOSTNAME: http://localhost:9180
      KC_HTTP_RELATIVE_PATH: /
      KC_HOSTNAME_STRICT: false
      KC_HOSTNAME_STRICT_HTTPS: false
      CACHE_OWNERS_AUTH_SESSIONS_COUNT: 2      
      JGROUPS_DISCOVERY_PROTOCOL: JDBC_PING
      JGROUPS_DISCOVERY_EXTERNAL_IP: kclocalws
      JGROUPS_DISCOVERY_PROPERTIES: "datasource_jndi_name=java:jboss/datasources/KeycloakDS,initialize_sql=\"CREATE TABLE IF NOT EXISTS JGROUPSPING (own_addr varchar(200) NOT NULL, cluster_name varchar(200) NOT NULL, created TIMESTAMP DEFAULT CURRENT_TIMESTAMP, ping_data BYTEA, constraint PK_JGROUPSPING PRIMARY KEY (own_addr, cluster_name))\",remove_all_data_on_view_change=true"
    networks:
      - kcaclnet

  lb:
    container_name: kcacllb
    image: nginx:alpine
    volumes:
      - ${PWD}/nginx_dynamic_node.conf:/etc/nginx/conf.d/default.conf
    ports:
      - "${KC_PORT}:${KC_PORT}"
    depends_on:
      - kc      
    networks:
      - kcaclnet

networks:
  kcaclnet:
    driver: bridge

volumes:
  postgres_data: