version: "3.9"
services:
  kcacldb:
      image: postgres:latest
      volumes:
        - postgres_data:/var/lib/postgresql/kcacldata
      environment:
        TZ: ${TZ}
        POSTGRES_USER: ${POSTGRES_USER}
        POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
        POSTGRES_DB: ${POSTGRES_DB}
        POSTGRES_HOST: ${DB_HOST}
      ports:
        - "${DB_PORT}:5432"
      networks:
        - authnet

  kcauth:
    image: quay.io/keycloak/keycloak:26.0.0
    ports:
      - "${KC_PORT}:8080"
      - "${KC_DEBUG_PORT}:${KC_DEBUG_PORT}"
    environment:    
       JAVA_OPTS_APPEND: >-
        -Dkeycloak.profile.feature.upload_scripts=enabled
        -Xms512m
        -Xmx2048m
        -XX:MetaspaceSize=96M
        -XX:MaxMetaspaceSize=256m
        -Djava.net.preferIPv4Stack=true
        -Djboss.modules.system.pkgs=org.jboss.byteman
       KC_BOOTSTRAP_ADMIN_USERNAME: ${KC_ADMIN}
       KC_BOOTSTRAP_ADMIN_PASSWORD: ${KC_ADMIN_PASSWORD}
       KC_HOSTNAME_ADMIN: http://localhost:9180
       KC_PROXY: edge
       KC_HOSTNAME: http://localhost:9180
       KC_METRICS_ENABLED: true
       KC_HEALTH_ENABLED: true
       KC_DB: postgres
       KC_DB_PASSWORD: ${POSTGRES_PASSWORD}
       KC_DB_SCHEMA: public
       KC_DB_USERNAME: ${POSTGRES_USER}
       KC_DB_URL_HOST: kcacldb       
       KC_DB_URL_DATABASE: ${POSTGRES_DB}
       KC_HTTP_RELATIVE_PATH: /
       KC_HOSTNAME_STRICT: false
       KC_HOSTNAME_STRICT_HTTPS: false
    depends_on:
      - kcacldb
    command:
      - start      
    networks:
      - authnet

networks:
  authnet:
    driver: bridge

volumes:
  postgres_data: